### PR TITLE
Added setting to enable/disable nimsuggest completions

### PR DESCRIPTION
**Pull request by onelivesleft**
Implements #131

### CODE REVIEW

**Comment by RSDuck** [comment]
this only disables suggestions, but not hovering or outlining as specified in #137

**Comment by onelivesleft** [comment]
It's not totally clear from #131 what the objective is.  Is it:

(A) The autocomplete popup is annoying and some users don't use it or want it, therefor it should be optional.  Other introspection actions which only happen when the user triggers them, such as hovering the mouse or executing a command are still useful, and should be retained.  

*or*

(B) nimsuggest uses resources and provides services which some users do not require, and so it should be optional.  When disabled, nimsuggest shouldn't run.

If it's (A) then this PR works as currently implemented.  If it's (B) then the actual mechanism should be detecting changes to the config option, and either registering or unregistering all the providers (and stopping the nimsuggest process).

Personally, (A) does it for me.

**Comment by RSDuck** [comment]
the author of the original pull request wrote:
> Should be a to disable any autocomplete features, such as nimsuggest and only use syntax highlighting.

"only use syntax highlighting" is what I would interpret as disabling any intellisense services. Though I agree with you that it's not completely clear what the authors intentions were.

**Comment by kosz78** [comment]
I think it is assume to disable nimsuggest in plugin at all, not only autocomplete feature.
The reason is that in big projects nimsuggest can be very slow and can take a lot of resources

**Comment by onelivesleft** [comment]
Urgh, I did not intend to close this.  Can it be reopened or will I make a new one?

**Pull request merged**
