### PR TITLE
Added new nimsuggest version.

### PR DESCRIPTION
**Pull request by oderwat**
We debugged nimsuggest with vscode-nim and added support for nimscript and changed file reloading to nimsuggest. Make sure you also use the most recent devel version of Nim.

### CODE REVIEW

**Comment by oderwat** [comment]
Well.. currently https://github.com/nim-lang/Nim/commit/8698de1742d577efa9dddc854d5cfb3f7b9fd1ff breaks vscode nimsuggest for me (again).

**Comment by oderwat** [comment]
We debugged and changed stuff in the compiler and nimsuggest again. This version should now work much better than before (esp. if config.nims is used for a project)

**Comment by kosz78** [comment]
@oderwat  I guess You accidentally added a binary file `nimx-0.5.3.vsix`

**Comment by oderwat** [comment]
Oh yes ... sorry. I will remove it!

**Comment by oderwat** [comment]
It's done (if you did not see it already)

**Comment by oderwat** [comment]
Is something holding you back tacking these changes?

**Comment by endragor** [comment]
@oderwat AFAIK it's at least the fact that this nimsuggest will not compile under release version of Nim. @kosz78 was planning to fix that along with something else, then make PR to [nimsuggest](https://github.com/nim-lang/nimsuggest).

**Comment by oderwat** [comment]
OK. But the new nimsuggest is coupled to devel changes anyway. I think he should better add the option that one can specify nimsuggests full path! And having the convenience fallback with compiling it like now. Another way would be to add multiple versions of nimsuggest.

@ Araq and me spent quite some time to fix stuff and adding functionality in the last days. If you know stuff to be added this is the time :)

**Comment by kosz78** [comment]
@oderwat I have committed a new version of nimsuggest with some additional changes (https://github.com/nim-lang/nimsuggest/pull/27)

**Comment by oderwat** [comment]
I would still prefer if vscode had a way to use nimsuggest from the system instead.

**Comment by kosz78** [comment]
@oderwat  I agree with you, but currently use nimsuggest required install or download source and compile nimble after that install nimsuggest using nimble, it more complex and hard to maintain from vscode, in future I would like to create some kind of wrapper over system nimsuggest and use json-protocol for VSCode https://github.com/Microsoft/language-server-protocol

**Pull request closed without merging**
